# Generated by Django 2.1.3 on 2019-10-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blogs_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='author',
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
